# Generated by Django 5.2.8 on 2025-11-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="asset_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("equity", "Equity"),
                    ("fx", "FX / Currencies"),
                    ("crypto", "Crypto"),
                    ("commodities", "Commodities"),
                    ("macro", "Macro / Rates"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="sentiment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bullish", "Bullish"),
                    ("bearish", "Bearish"),
                    ("neutral", "Neutral"),
                ],
                max_length=20,
            ),
        ),
    ]
